### ISSUE TITLE
HaskellKernel times out running tests in a clean repo

### ISSUE THREAD

**Issue by sorear** [seL4/l4v#74] opened 2020-09-06 09:07 UTC
```
user@in-container:/host/r/l4v$ time ./run_tests  -j1 HaskellKernel
Testing for L4V_ARCH=ARM:
Testing Orphanage for ARM
Running 1 test(s)...
  Started HaskellKernel ...         
  Finished HaskellKernel             TIMEOUT *   ( 0:01:56 real,  0:30:03 cpu,  0.77GB)

------------------------------------------------------------------------
TEST TIMEOUT: HaskellKernel

...
[18 of 75] Compiling SEL4.Machine     ( src/SEL4/Machine.lhs, dist/arm/build/SEL4/Machine.o )
[19 of 75] Compiling SEL4.API.InvocationLabels ( src/SEL4/API/InvocationLabels.lhs, dist/arm/build/SEL4/API/InvocationLabels.o )
[20 of 75] Compiling SEL4.API.Failures.ARM ( src/SEL4/API/Failures/ARM.lhs, dist/arm/build/SEL4/API/Failures/ARM.o )
[21 of 75] Compiling SEL4.API.Types.ARM ( src/SEL4/API/Types/ARM.lhs, dist/arm/build/SEL4/API/Types/ARM.o )
[22 of 75] Compiling SEL4.API.Types   ( src/SEL4/API/Types.lhs, dist/arm/build/SEL4/API/Types.o )
[23 of 75] Compiling SEL4.API.Failures ( src/SEL4/API/Failures.lhs, dist/arm/build/SEL4/API/Failures.o )
[24 of 75] Compiling SEL4.Machine.Target ( src/SEL4/Machine/Target.lhs, dist/arm/build/SEL4/Machine/Target.o )
[25 of 75] Compiling SEL4.Object.Structures[boot] ( src/SEL4/Object/Structures.lhs-boot, dist/arm/build/SEL4/Object/Structures.o-boot )
[26 of 75] Compiling SEL4.Object.Structures.ARM ( src/SEL4/Object/Structures/ARM.lhs, dist/arm/build/SEL4/Object/Structures/ARM.o )
[27 of 75] Compiling SEL4.Object.Structures ( src/SEL4/Object/Structures.lhs, dist/arm/build/SEL4/Object/Structures.o )
[28 of 75] Compiling SEL4.Model.PSpace[boot] ( src/SEL4/Model/PSpace.lhs-boot, dist/arm/build/SEL4/Model/PSpace.o-boot )
[29 of 75] Compiling SEL4.API.Invocation.ARM ( src/SEL4/API/Invocation/ARM.lhs, dist/arm/build/SEL4/API/Invocation/ARM.o )
[30 of 75] Compiling SEL4.API.Invocation ( src/SEL4/API/Invocation.lhs, dist/arm/build/SEL4/API/Invocation.o )
[31 of 75] Compiling SEL4.Model.StateData.ARM ( src/SEL4/Model/StateData/ARM.lhs, dist/arm/build/SEL4/Model/StateData/ARM.o )
[32 of 75] Compiling SEL4.Model.StateData ( src/SEL4/Model/StateData.lhs, dist/arm/build/SEL4/Model/StateData.o )
[33 of 75] Compiling SEL4.Model.Preemption ( src/SEL4/Model/Preemption.lhs, dist/arm/build/SEL4/Model/Preemption.o )
[34 of 75] Compiling SEL4.Model.PSpace ( src/SEL4/Model/PSpace.lhs, dist/arm/build/SEL4/Model/PSpace.o )
[35 of 75] Compiling SEL4.Model.Failures ( src/SEL4/Model/Failures.lhs, dist/arm/build/SEL4/Model/Failures.o )
[36 of 75] Compiling SEL4.Model.Syscall ( src/SEL4/Model/Syscall.lhs, dist/arm/build/SEL4/Model/Syscall.o )
[37 of 75] Compiling SEL4.Model       ( src/SEL4/Model.lhs, dist/arm/build/SEL4/Model.o )
[38 of 75] Compiling SEL4.Object.Interrupt[boot] ( src/SEL4/Object/Interrupt.lhs-boot, dist/arm/build/SEL4/Object/Interrupt.o-boot )
[39 of 75] Compiling SEL4.Object.Instances.ARM ( src/SEL4/Object/Instances/ARM.lhs, dist/arm/build/SEL4/Object/Instances/ARM.o )
[40 of 75] Compiling SEL4.Object.Instances ( src/SEL4/Object/Instances.lhs, dist/arm/build/SEL4/Object/Instances.o )
[41 of 75] Compiling SEL4.Object.Endpoint[boot] ( src/SEL4/Object/Endpoint.lhs-boot, dist/arm/build/SEL4/Object/Endpoint.o-boot )
[42 of 75] Compiling SEL4.Object.CNode[boot] ( src/SEL4/Object/CNode.lhs-boot, dist/arm/build/SEL4/Object/CNode.o-boot )
[43 of 75] Compiling SEL4.Kernel.VSpace[boot] ( src/SEL4/Kernel/VSpace.lhs-boot, dist/arm/build/SEL4/Kernel/VSpace.o-boot )
[44 of 75] Compiling SEL4.Kernel.Thread[boot] ( src/SEL4/Kernel/Thread.lhs-boot, dist/arm/build/SEL4/Kernel/Thread.o-boot )
[45 of 75] Compiling SEL4.Kernel.Init[boot] ( src/SEL4/Kernel/Init.lhs-boot, dist/arm/build/SEL4/Kernel/Init.o-boot )
[46 of 75] Compiling SEL4.Kernel.CSpace[boot] ( src/SEL4/Kernel/CSpace.lhs-boot, dist/arm/build/SEL4/Kernel/CSpace.o-boot )
[47 of 75] Compiling SEL4.Object.Interrupt.ARM ( src/SEL4/Object/Interrupt/ARM.lhs, dist/arm/build/SEL4/Object/Interrupt/ARM.o )
[48 of 75] Compiling SEL4.Kernel.BootInfo ( src/SEL4/Kernel/BootInfo.lhs, dist/arm/build/SEL4/Kernel/BootInfo.o )
[49 of 75] Compiling SEL4.Object.TCB[boot] ( src/SEL4/Object/TCB.lhs-boot, dist/arm/build/SEL4/Object/TCB.o-boot )
[50 of 75] Compiling SEL4.Object.Notification ( src/SEL4/Object/Notification.lhs, dist/arm/build/SEL4/Object/Notification.o )
[51 of 75] Compiling SEL4.Object.Interrupt ( src/SEL4/Object/Interrupt.lhs, dist/arm/build/SEL4/Object/Interrupt.o )
[52 of 75] Compiling SEL4.Object.Endpoint ( src/SEL4/Object/Endpoint.lhs, dist/arm/build/SEL4/Object/Endpoint.o )
[53 of 75] Compiling SEL4.Kernel.VSpace.ARM ( src/SEL4/Kernel/VSpace/ARM.lhs, dist/arm/build/SEL4/Kernel/VSpace/ARM.o )
make: *** [Makefile:40: build-arm] Interrupt
No timing log for HaskellKernel was found.
  (in /isabelle/ARM/log/HaskellKernel_times.txt)

------------------------------------------------------------------------


0/1 tests succeeded.

Tests failed.


real    1m56.859s
user    10m48.749s
sys     7m39.359s
user@in-container:/host/r/l4v$ nproc
64
user@in-container:/host/r/l4v$ git clean -dfx
Removing misc/regression/__pycache__/
Removing spec/haskell/.cabal-sandbox/
Removing spec/haskell/.stack-work/
Removing spec/haskell/cabal.sandbox.config
Removing spec/haskell/dist/
Removing spec/haskell/src/SEL4/Kernel/CSpace.lhs-boot
Removing spec/haskell/src/SEL4/Kernel/FaultHandler.lhs-boot
Removing spec/haskell/src/SEL4/Kernel/Init.lhs-boot
Removing spec/haskell/src/SEL4/Kernel/Thread.lhs-boot
Removing spec/haskell/src/SEL4/Kernel/VSpace.lhs-boot
Removing spec/haskell/src/SEL4/Model/PSpace.lhs-boot
Removing spec/haskell/src/SEL4/Object/CNode.lhs-boot
Removing spec/haskell/src/SEL4/Object/Endpoint.lhs-boot
Removing spec/haskell/src/SEL4/Object/IOPort/X64.lhs-boot
Removing spec/haskell/src/SEL4/Object/Interrupt.lhs-boot
Removing spec/haskell/src/SEL4/Object/ObjectType.lhs-boot
Removing spec/haskell/src/SEL4/Object/TCB.lhs-boot
Removing spec/haskell/stack.yaml.lock
user@in-container:/host/r/l4v$ time ./run_tests  -j1 HaskellKernel --no-timeouts
Testing for L4V_ARCH=ARM:
Testing Orphanage for ARM
Running 1 test(s)...
  Started HaskellKernel ...         
  Finished HaskellKernel             passed      ( 0:02:48 real,  1:23:51 cpu,  0.75GB)


1/1 tests succeeded.

All tests passed.


real    2m49.177s
user    48m45.059s
sys     35m36.153s
```

**Comment by sorear** [comment] 2020-09-06 10:32
Limiting the number of threads with `taskset` is counterproductive, user time goes way up.  Setting `jobs: 1` in `~/.cabal/config`, on the other hand, is wildly effective:

```
user@in-container:/host/r/l4v$ git clean -dfx
Removing misc/regression/__pycache__/
Removing spec/haskell/.cabal-sandbox/
Removing spec/haskell/.stack-work/
Removing spec/haskell/cabal.sandbox.config
Removing spec/haskell/stack.yaml.lock
user@in-container:/host/r/l4v$ time ./run_tests  -j1 HaskellKernel --no-timeouts
Testing for L4V_ARCH=ARM:
Testing Orphanage for ARM
Running 1 test(s)...
  Started HaskellKernel ...         
  Finished HaskellKernel             passed      ( 0:01:52 real,  0:01:41 cpu,  0.74GB)


1/1 tests succeeded.

All tests passed.


real    1m53.019s
user    1m47.143s
sys     0m6.447s
```

Setting `jobs: 64` goes back to the old timings, so I don't think I'm missing a cache here.

**Comment by lsf37** [comment] 2020-09-08 01:34
Very strange. Are you using one of the docker images to build from? Which one?

**Comment by sorear** [comment] 2020-09-08 03:57
`trustworthysystems/l4v-riscv`

**Comment by lsf37** [comment] 2020-09-10 04:00
Thanks. I still can't reproduce. I've set `jobs: 64` in `~/.cabal/config`, but am still getting a normal run.

Is the rest of the `~/.cabal/config` from the container or mounted from your user home? If from user, would you be Ok posting the rest of it? Maybe there is some other option that conflicts with something.

**Comment by heb1001** [comment] 2020-09-10 08:25
I think I saw a problem with the same symptoms.

On the first run for a clean build there is some stuff that gets downloaded.

There were two downloads causing problems.

The first one was:

stack —install-ghc build cabal-install

The second one was:

stack exec — ./stack-path cabal v1-update

If you start with a clean build and throttle the network (to maybe 10kB/s)
you ought to be able to recreate the timeouts.

Harry

**Comment by lsf37** [comment] 2020-09-10 08:31
Ok, so these would be download issues, which we could fix larger timeouts. I don't think there's much we can do about making them faster. Downloading an entire ghc installation + a bunch of cabal packages is relatively large if anything happens with the network.

Maybe we could try to provide that within the docker container, though. That would at least all come from the same source then (docker).

@sorear is that also what you're seeing or do you think your problem is different?

**Comment by heb1001** [comment] 2020-09-10 08:41
Perhaps a separate Haskell test with a longer timeout just before/after the
Isabelle test to force the download.

**Comment by sorear** [comment] 2020-09-10 10:23
I believe I am seeing a different issue.  When it times out, there are 64 ghc processes running at near-full CPU.

**Comment by lsf37** [comment] 2020-09-10 11:02
Reading about the default for jobs on the cabal bug tracker, the main complaint is that a too high number of jobs might run out of memory very quickly. That doesn't seem to be the case here, though, at least not according to the output of `time` above. 

Do lower job numbers like 2, 4 or 8 have the same problem? I could just set them manually to something like 2 for this sandbox -- the Haskell compile time is very low compared to the proofs, so I don't think we'd mind a bit less parallelism.

On the off chance that he's seen something like this before, let me also ping @mbrcknl for this.

**Comment by mbrcknl** [comment] 2020-09-10 11:26
The current timeout is based on total cpu time, not real time. I don't think I've ever tried this on a box with 64 CPUs. :-) With that many, you'll get less than 2 minutes real time if they're fully occupied. I guess the single-threaded speed might be slower than on the 4-6 core boxes we're accustomed to, so 30 minutes total CPU time is not enough? That's the only possible explanation I can think of so far.

I suggest changing the `cpu-timeout=1800` in `spec/tests.xml` to `timeout=600`, and see what happens.

**Comment by mbrcknl** [comment] 2020-09-10 14:27
Sorry, I hadn't fully registered your comment that with `jobs: 1`, it finishes in even less time. In light of that, my previous comment doesn't make sense.

That is indeed very strange. I suppose you've tried building some other random large Haskell packages on this machine, without seeing this issue?

**Comment by lsf37** [comment] 2020-12-02 04:37
Since we don't seem to be able to get to the bottom of it, and we do have a workaround (setting `jobs: 1` in `~/.cabal/config`) I'll close the issue.

If anyone feels like investigating deeper and/or new problems turn up with this, feel free to re-open.

**Closed by lsf37** 2020-12-02 04:37 UTC
Labels: CI
